"""describe migration

Revision ID: 9b05a42135a3
Revises: c8d6998c10ca
Create Date: 2026-06-24 13:37:31.079952+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9b05a42135a3'
down_revision: str | None = 'c8d6998c10ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###