"""add content projects table

Revision ID: a0ca75673050
Revises: 9b05a42135a3
Create Date: 2026-06-26 07:12:14.731750+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0ca75673050'
down_revision: str | None = '9b05a42135a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_content_projects_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_content_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_projects'))
    )
    op.create_index(op.f('ix_content_projects_brand_id'), 'content_projects', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_projects_content_type'), 'content_projects', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_projects_owner_id'), 'content_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_content_projects_platform'), 'content_projects', ['platform'], unique=False)
    op.create_index(op.f('ix_content_projects_status'), 'content_projects', ['status'], unique=False)
    op.create_index(op.f('ix_content_projects_title'), 'content_projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_projects_title'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_status'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_platform'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_owner_id'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_content_type'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_brand_id'), table_name='content_projects')
    op.drop_table('content_projects')
    # ### end Alembic commands ###