"""add generated contents table

Revision ID: a1cfaf749a17
Revises: a0ca75673050
Create Date: 2026-06-29 09:01:18.377657+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1cfaf749a17'
down_revision: str | None = 'a0ca75673050'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('generation_engine', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('tone', sa.String(length=120), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('brand_context', sa.JSON(), nullable=True),
    sa.Column('variations', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_contents'))
    )
    op.create_index(op.f('ix_generated_contents_content_type'), 'generated_contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_generated_contents_generation_engine'), 'generated_contents', ['generation_engine'], unique=False)
    op.create_index(op.f('ix_generated_contents_id'), 'generated_contents', ['id'], unique=False)
    op.create_index(op.f('ix_generated_contents_platform'), 'generated_contents', ['platform'], unique=False)
    op.create_index(op.f('ix_generated_contents_project_id'), 'generated_contents', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_contents_project_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_platform'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_generation_engine'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_content_type'), table_name='generated_contents')
    op.drop_table('generated_contents')
    # ### end Alembic commands ###